// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHqV0S0FNTuLdOkbP-dUglzW83OCyRDcI',
    appId: '1:6837170298:android:b037230994a5f984164bc3',
    messagingSenderId: '6837170298',
    projectId: 'shram-saathi-py098a',
    storageBucket: 'shram-saathi-py098a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjtI8--q66mhzc_kc3Bh7eDWUHAv7xbck',
    appId: '1:6837170298:ios:89b4c64346b31d99164bc3',
    messagingSenderId: '6837170298',
    projectId: 'shram-saathi-py098a',
    storageBucket: 'shram-saathi-py098a.firebasestorage.app',
    iosBundleId: 'com.example.gramsetuApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCthy7w0WG4R0MoHeb2dMe5TNTyPSlb5ck',
    appId: '1:6837170298:web:c327312bd7d0b61a164bc3',
    messagingSenderId: '6837170298',
    projectId: 'shram-saathi-py098a',
    authDomain: 'shram-saathi-py098a.firebaseapp.com',
    storageBucket: 'shram-saathi-py098a.firebasestorage.app',
  );

}